apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: ${name}
build:
  artifacts:
    - image: ${name}
      sync:
        auto: true
      jib:
        type: gradle
        fromImage: 'amazoncorretto:11'
        args: [ ]
    - image: ${name}-logic-executor
      sync:
        auto: true
      custom:
        buildCommand: |
          cd ../logic-executor && ./mvnw clean package && docker build --pull --rm -f "src/main/docker/Dockerfile.jvm" -t $IMAGE .

profiles:
  - name: local
    deploy:
      kustomize:
        paths: ["build/manifest/k8s/kustomize/local"]
        buildArgs: ["--enable-helm", "--load-restrictor=LoadRestrictionsNone"]
    build:
      local:
        push: false
      tagPolicy:
        gitCommit: { }
  - name: dev
    patches:
      - op: delete
        path: /build/artifacts/1
    deploy:
      kustomize:
        paths: [ "build/manifest/k8s/kustomize/dev" ]
        buildArgs: [ "--enable-helm", "--load-restrictor=LoadRestrictionsNone" ]
    build:
      local:
        push: false
      tagPolicy:
        envTemplate:
          template: "{{.TAG}}"

