apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../helm

helmCharts:
  - name: ${name}
    includeCRDs: false
    releaseName: ${name}
    version: ${chart_version}
    valuesInline: {}
