---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ${name}-service
spec:
  hosts:
  - "${name}-service.${namespace}-dev.svc.cluster.local"
  http:
  - route:
    - destination:
        port:
          number: 8080
        host: ${name}-service

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ${name}-service-api
spec:
  hosts:
  - "api.dev.${fqdn}"
  gateways:
  - ${entry}
  http:
  - match:
    - uri:
        prefix: /api/${ownerDomain}/${name}
    route:
    - destination:
        port:
          number: 8080
        host: ${name}-service

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ${name}-service
spec:
  host: ${name}-service
