apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ${name}
    files:
      - ${build_relative_path}resources/main/micrc.properties

secretGenerator:
  - name: ${name}-database
    literals:
      - database.host=database-mysql
      - database.port=3306
      - database.user=${name}
      - database.pass=${name}
  - name: ${name}-cache
    literals:
      - cache.host=cache-redis-master
      - cache.port=6379
      - cache.pass=${name}
  - name: ${name}-memory-db
    literals:
      - memory-db.host=cache-redis-master
      - memory-db.port=6379
      - memory-db.pass=${name}
  - name: ${name}-broker
    literals:
      - broker.host=broker-rabbitmq
      - broker.port=5672
      - broker.user=${name}
      - broker.pass=${name}

resources:
  - ../base