apiVersion: v1
kind: Service
metadata:
  name: {{ include "${name}.fullname" . }}
  labels:
    {{- include "${name}.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "${name}.selectorLabels" . | nindent 4 }}


---
# temp NodePort service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "${name}.fullname" . }}-nodeport
  labels:
    {{- include "${name}.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "${name}.selectorLabels" . | nindent 4 }}