apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ${name}-service
    files:
      - ../../../../../resources/main/micrc.properties

helmGlobals:
  chartHome: ../../helm

helmCharts:
  - name: ${name}
    includeCRDs: false
    releaseName: ${name}
    version: ${version}
    # 修改values 文件
    valuesInline:
      podAnnotations:
        # 为我们所有的pod 治理 网络 （实现服务治理）
        sidecar.istio.io/inject: 'true'
      ${database_secret_inlineValues}
      ${cache_secret_inlineValues}
      ${broker_secret_inlineValues}
      ${memdb_secret_inlineValues}
