apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: ${name}-docker-registry
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=../docker-config.json

resources:
  - ../base
  - ./sealed-secret.yaml

patchesStrategicMerge:
  - |-
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    metadata:
      name: ${name}
    \$patch: delete

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ${name}-docker-registry
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["alpha"]
    target:
      kind: Deployment
