apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ${name}
    files:
      - ${build_relative_path}resources/main/micrc.properties

secretGenerator:
  - name: ${name}-database
    literals:
      - database.host=database-mysql
      - database.port=3306
      - database.dbname=${underline_name}
      - database.username=${underline_name}
      - database.password=${underline_name}
  - name: redis-admin
    literals:
      - cache.host=cache-redis-master
      - cache.port=6379
      - cache.password=cache
  - name: memory-db-admin
    literals:
      - memory-db.host=cache-redis-master
      - memory-db.port=6379
      - memory-db.password=cache
  - name: kafka-admin
    literals:
      - broker.host=broker-kafka
      - broker.port=9092
      - broker.user=kafka
      - broker.pass=kafka

helmCharts:
  - name: mysql
    repo: https://charts.bitnami.com/bitnami
    includeCRDs: false
    releaseName: database
    version: 9.4.1
    valuesInline:
      image:
        tag: 8.0.30
      architecture: standalone
      auth:
        rootPassword: root
        createDatabase: true
        database: ${underline_name}
        username: ${underline_name}
        password: ${underline_name}
      primary:
        persistence:
          enabled: false
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    includeCRDs: false
    releaseName: cache
    version: 17.3.5
    valuesInline:
      image:
        tag: 6.2
      architecture: standalone
      auth:
        enabled: true
        sentinel: false
        password: cache
      master:
        persistence:
          enabled: false
  - name: kafka
    repo: https://charts.bitnami.com/bitnami
    includeCRDs: false
    releaseName: broker
    version: 20.0.1
    valuesInline:
      image:
        tag: 3.3.1-debian-11-r22
      auth:
        clientProtocol: plaintext
      persistence:
        enabled: false
      zookeeper:
        enabled: true
        replicaCount: 1


resources:
  - ../base

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["local"]
    target:
      kind: Deployment
# 临时注释 需寻找kafka就绪探针的实现方式,该种方式不可行
#  - patch: |-
#      - op: add
#        path: /spec/template/spec/initContainers/2
#        value:
#          name: broker-init
#          image: curlimages/curl
#          command: ['sh', '-c', 'until curl broker-kafka:9092; do echo waiting for broker; sleep 2; done;']
#    target:
#      kind: Deployment
